/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ShelleyPart {
  isScript: boolean
  pubkeyHash?: string
  pointer?: string
}
export interface AddressDiagnostic {
  kind: string
  network?: string
  paymentPart?: ShelleyPart
  delegationPart?: ShelleyPart
}
export interface Output {
  error?: string
  bytes?: string
  address?: AddressDiagnostic
}
export function parseAddress(raw: string): Output
