/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ShelleyPart {
  isScript: boolean
  hash?: string
  pointer?: string
}
export interface AddressDiagnostic {
  kind: string
  network?: string
  paymentPart?: ShelleyPart
  delegationPart?: ShelleyPart
  byronCbor?: string
}
export interface Output {
  error?: string
  bytes?: string
  address?: AddressDiagnostic
}
export interface Attribute {
  topic?: string
  value?: string
}
export interface Section {
  topic?: string
  identity?: string
  error?: string
  attributes: Array<Attribute>
  bytes?: string
  children: Array<Section>
}
export function parseAddress(raw: string): Output
export interface SectionValidation {
  section: Section
  validations: Validations
}
export function safeParseTx(raw: string): SectionValidation
export function safeParseBlock(raw: string): Section
export interface Validation {
  name: string
  value: boolean
  description: string
}
export interface Validations {
  validations: Array<Validation>
  era: string
}
