name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: napi-pallas
        working-directory: napi-pallas
        run: yarn install && yarn run build

      - name: web
        working-directory: web
        run: yarn install && yarn run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            web/build
            web/package.json
            napi-pallas/index.js
            napi-pallas/package.js
            napi-pallas/yarn.lock
            napi-pallas/*.node
            napi-pallas/npm
