name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: yarn install
        run: yarn install

      - name: napi-pallas build
        run: yarn workspaces run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            **/build
            **/dist
