name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: napi-pallas
        working-directory: napi-pallas
        run: yarn install && yarn run build

      - name: web
        working-directory: web
        run: yarn install && yarn run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            web/build
            web/package.json
            napi-pallas/index.js
            napi-pallas/package.js
            napi-pallas/yarn.lock
            napi-pallas/*.node
            napi-pallas/npm

  docker:
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/txpipe/laceanatomy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/txpipe
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
